SportStore.WebUI/Models/CartIndexViewModel.cs
using Domain.Entities;

namespace SportStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

SportStore.WebUI/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;


namespace SportStore.WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

SportStore.WebUI/Models/PagingInfo.cs
using System;

namespace SportStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

SportStore.WebUI/Models/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using Domain.Entities;

namespace SportStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

SportStore.WebUI/Controllers/AccountController.cs
using System.Web.Mvc;
using SportStore.WebUI.Infrastructure.Abstract;
using SportStore.WebUI.Models;

namespace SportStore.WebUI.Controllers
{
    public class AccountController : Controller
    {
        IAuthProvider authProvider;

        public AccountController(IAuthProvider auth) {
            authProvider = auth;
        }

        public ViewResult Login() {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl) {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(model.UserName, model.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect username or password");
                    return View();
                }
            }
            else {
                return View();
            }
        }
    }
}

SportStore.WebUI/Controllers/AdminController.cs
using System.Linq;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;

namespace SportStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductRepository repository;

        public AdminController(IProductRepository repo) {
            repository = repo;
        }

        public ViewResult Index() {
            return View(repository.Products);
        }

        public ViewResult Edit(int productId) {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else {
                return View(product);
            }
       }

       public ViewResult Create() {
           return View("Edit", new Product());     
       }

       public ActionResult Duplicate(int productId)
       {
           Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
           Product newProduct = new Product { 
                Name = product.Name + "--copy",
                Description = product.Description,
                Price = product.Price,
                Category = product.Category
           };
           repository.SaveProduct(newProduct);
           return RedirectToAction("Index");
       }

       [HttpPost]
       public ActionResult Delete(int productId) {
           Product deletedProduct = repository.DeleteProduct(productId);
           if (deletedProduct != null) {
               TempData["message"] = string.Format("{0} was deleted", deletedProduct.Name);
           }
           return RedirectToAction("Index");
       } 
    }
}

SportStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using SportStore.WebUI.Models;

namespace SportStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor proc) {
            repository = repo;
            orderProcessor = proc;
        }

        public ViewResult Index(Cart cart, string returnUrl) {
            return View(new CartIndexViewModel {  Cart = cart, ReturnUrl = returnUrl });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl) {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null) {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });

        }

        public PartialViewResult Summary(Cart cart) {
            return PartialView(cart);
        }

        public ViewResult Checkout() {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails) {
            if (cart.Lines.Count() == 0) {
                ModelState.AddModelError("", "Sorry, your order is empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else {
                return View(shippingDetails);
            }
        }
    }
}

SportStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;

namespace SportStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo) {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null, bool horizontalLayout = false) {

            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            //string viewName = horizontalLayout ? "MenuHorizontal" : "Menu";

            //return PartialView(horizontalLayout ? "MenuHorizontal" : "Menu", categories);

            return PartialView("FlexMenu", categories);
        }
    }
}

SportStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Entities;
using SportStore.WebUI.Models;

namespace SportStore.WebUI.Controllers
{
    public class ProductController : Controller
    {

        private IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository productRepository) {
            this.repository = productRepository;
        }

        public ViewResult List(string category, int page = 1) {

            ProductsListViewModel model = new ProductsListViewModel { 
                Products = repository.Products.Where(p=>category == null || p.Category == category).OrderBy(p=>p.ProductID).Skip((page-1)*PageSize).Take(PageSize),
                PagingInfo = new PagingInfo {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        repository.Products.Count() :
                        repository.Products.Where(e=>e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

SportStore.WebUI/Views/Admin/Edit.cshtml
@model Domain.Entities.Product

@{
    ViewBag.Title = "Admin product edit : " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>@Model.Name</h1>

<div class="panel">
    <div class="panel-heading">
        <h3>Admin product edit : @Model.Name</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin")) { 
        <div class="panel-body">
            @Html.HiddenFor(m=>m.ProductID)
            @foreach (var property in ViewData.ModelMetadata.Properties) {
                if (property.PropertyName != "ProductID") { 
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description") { 
                            @Html.TextArea(property.PropertyName, null, new { @class="form-control", rows=5})
                        }else{
                            @Html.TextBox(property.PropertyName, null, new { @class="form-control"})
                        }

                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }
        </div>
        
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary"/>
            @Html.ActionLink("Cancel and return to list", "Index", null, new { @class="btn btn-default"})
        </div>
    }
</div>

SportStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Product>

@{
    ViewBag.Title = "Admin product list";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All products</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th colspan="2" class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model) { 
                <tr>
                    <td class="text-right">@item.ProductID</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
                    <td class="text-right">@item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin")) { 
                            @Html.Hidden("ProductID", item.ProductID)
                            <input type="submit" class="btn btn-default btn-xs" value="Delete" />
                        }
                    </td>
                    <td class="text-center">
                        @Html.ActionLink("Duplicate", "Duplicate", new { item.ProductID }, new { @class="btn btn-info btn-xs" })
                    </td>
                </tr>
            }
        </table>
    </div>

    <div class="panel-footer">
        @Html.ActionLink("Add new product", "Create", null, new { @class="btn btn-default"})
    </div>
</div>

SportStore.WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails
@{
    ViewBag.Title = "SportStore : Checkout";
}

<h2>Checkout</h2>

<p>Please enter your details</p>

@using (Html.BeginForm()) { 
    
    @Html.ValidationSummary()
    <h3>Ship to:</h3>
    
    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(x => x.Name, new { @class="form-control"})
    </div>
    
    <h3>Address: </h3>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label for="@(property.PropertyName)">@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new{@class="form-control"})
            </div>
        }
    }
    
    <h3>Options:</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x=>x.GiftWrap)
            Gift wrapping
        </label>
    </div>
    
    <div class="text-center">
        <input type="submit" class="btn btn-primary" value="Complete order" />
    </div>
}

SportStore.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Order Completed";
}

<h2>Thank you for your order</h2>

SportStore.WebUI/Views/Cart/Index.cshtml
@model SportStore.WebUI.Models.CartIndexViewModel
@{
    ViewBag.Title = "Sport Store : Your Cart";
}

<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<h2>Your Cart</h2>

<table class="table" id="cartTable">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines) { 
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-right">
                    @((line.Quantity*line.Product.Price).ToString("c"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart")){
                        @Html.Hidden("ProductId", line.Product.ProductID)
                        @Html.HiddenFor(x=>x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove">
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    @Html.ActionLink("Checkout Now", "Checkout", null, new { @class="btn btn-primary"})
</div>

SportStore.WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn"})
</div>

<div class="navbar-text navbar-right">
    <b>Your cart:</b>
    @Model.Lines.Sum(x=>x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
</div>

SportStore.WebUI/Views/Nav/FlexMenu.Mobile.cshtml
@model IEnumerable<string>

<div data-role="navbar">
    <ul>
        <li>
            @Html.ActionLink("Home", "List", "Product", null,
                new { @class = "" })
        </li>

        @foreach (var link in Model)
        {
            <li>
                @Html.RouteLink(link, new
                    {
                        controller = "Product",
                        action = "List",
                        category = link,
                        page = 1
                    }, new
                    {
                        data_transition = "fade",
                        @class = (link == ViewBag.SelectedCategory ? "ui-btn-active" : null)
                    }
                )
            </li>
        }
    </ul>
</div>

SportStore.WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{
    bool horizontal = ((bool)(ViewContext.RouteData.Values["horizontalLayout"] ?? false));
    string wrapperClasses = horizontal ? "btn-group btn-group-sm btn-group-justified" : null;
}

<div class="@wrapperClasses">
    @Html.ActionLink("Home", "List", "Product", null,
        new { @class = horizontal ? "btn btn-default btn-sm" : "btn btn-block btn-default btn-lg" })

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
            {
                controller = "Product",
                action = "List",
                category = link,
                page = 1
            }, new
            {
                @class = (horizontal ? "btn btn-default btn-sm" : "btn btn-block btn-default btn-lg")
                    + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
            }
        )
    }

</div>

SportStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home","List","Product",null,
    new {@class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model) { 
    @Html.RouteLink(link, new
        {
            controller = "Product",
            action = "List",
            category = link,
            page = 1
        }, new { 
            @class = "btn btn-block btn-default btn-lg"
                + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
        }
    )
}

SportStore.WebUI/Views/Nav/MenuHorizontal.cshtml
@model IEnumerable<string>

<div class="btn-group btn-group-sm btn-group-justified">
    @Html.ActionLink("Home", "List", "Product",null, new { @class="btn btn-default btn-sm"})

    @foreach (var link in Model){
        @Html.RouteLink(link, new
           {
               controller = "Product",
               action = "List",
               category = link,
               page = 1
           }, new { 
               @class="btn btn-default btn-sm"
               + (link == ViewBag.SelectedCategory ? " btn-primary":"")
           })
    }
</div>

SportStore.WebUI/Views/Product/List.cshtml
@using Domain.Entities
@model SportStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products List";
}

@foreach (var p in Model.Products) { 
    @Html.Partial("ProductSummary", p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

SportStore.WebUI/Views/Shared/ProductSummary.Mobile.cshtml
@model Domain.Entities.Product

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>

    <div class="ui-grid-b">
        <div class="ui-block-a">
            @Model.Description
        </div>
        <div class="ui-block-b">
            <strong>@Model.Price.ToString("c")</strong>
        </div>
        <div class="ui-block-c">
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.ProductID)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" data-inline="true" data-mini="true" value="Add to cart">
                </div>
            }
        </div>
    </div>
</div>

SportStore.WebUI/Views/Shared/ProductSummary.cshtml
@model Domain.Entities.Product

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>

    @using (Html.BeginForm("AddToCart", "Cart")) { 
        <div class="pull-right">
            @Html.HiddenFor(x=>x.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart">
        </div>
    }

    <span class="lead">@Model.Description</span>

</div>

SportStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css?id=1" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">

        @if (TempData["message"] != null) { 
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    
    <link href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css?id=1" rel="stylesheet" type="text/css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>SportStore</h3>
            @Html.Action("Menu","Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-dividertheme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

SportStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css?id=1" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            @Html.ActionLink("SPORT STORE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            @Html.Action("Summary", "Cart")
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        <div class="visible-xs">
            @Html.Action("Menu","Nav",new{horizontalLayout=true})
        </div>
        <div class="row panel">
            <div id="categories" class="col-sm-3 hidden-xs">
                @Html.Action("Menu", "Nav")
            </div>
            <div class="col-sm-9 col-xs-12">
                @RenderBody()
            </div> 
        </div>
        
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>